# Generated by Django 5.0.3 on 2024-03-22 12:11

import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessPal', '0002_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.UUIDField()),
                ('target', models.UUIDField()),
            ],
            managers=[
                ('follows', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('white', models.UUIDField(null=True)),
                ('black', models.UUIDField(null=True)),
                ('moves', models.JSONField()),
            ],
            managers=[
                ('games', django.db.models.manager.Manager()),
            ],
        ),
    ]
